import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [response, setResponse] = useState(null);

  const handleSubmit = async () => {
    try {
      const result = await axios.post("http://localhost:37564/accounts/confirm/save", 
        {
          key: "value",
        },
        {
          headers: {
            "Content-Type": "application/json",
          },
          withCredentials: true,
        }
      );
  
      if (result.status === 200) {
        const data = result.data;
        setResponse(data); // レスポンスデータを保存
      } else {
        console.error("エラーが発生しました");
      }
    } catch (error) {
      console.error("通信エラーが発生しました", error);
    }
  };
  return (
    <>
      <Head>
        <title>リダイレクト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <h1>hello world!</h1>
        <button onClick={handleSubmit}>送信</button>
        {response && <pre>{JSON.stringify(response, null, 2)}</pre>}
      </div>
    </>
  );
}
